source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'Unity-iPhone' do
    pod 'GooglePlayGames', '5.1.2'
    pod 'Google-Mobile-Ads-SDK', '~> 7.8'
    #pod 'GoogleSignIn', '~> 2.4.0'
    #pod 'UnityAds', '~> 1.5'
    pod 'AdColony', '~> 3.0'
    pod 'GoogleMobileAdsMediationAdColony', '~> 3.0'
    pod 'ChartboostSDK', '~> 6.5'
    pod 'Crashlytics', '~> 3.8'
end
